using UnityEngine;


namespace SG
{
	public class AIBossCharacterManager : MonoBehaviour
	{
		// GIVE THIS A.I A UNIQUE ID
		// WHEN THIS A.I SPAWNED, CHECK OUT SAVE FILE 
		// IF THE SAVE FILE DOES NOT CONTAIN A BOSS MONSTER WITH THIS ID, ADD IT
		// IF IT IS PRESENT, CHECK IF THE BOSS HAS BEEN DEFEATED
		// IF THE BOSS HAS BEEN DEFEATED, DISABLE THE BOSS MONSTER AND ITS COMPONENTS
		// IF THE BOSS HAS NOT BEEN DEFEATED, ALLOW THIS OBJECT TO CONTINUE TO BE ACTIVE
	}
}
